/**
Controller: Constants
Important constants used in the game.
Pending:
- Load from back-end when the services are incorporated.
*/

// Values may come from service once back-end is implemented.

export const Constants = {

  maxTokensMore : 5,
  maxTokens5050 : 2,
  maxTokensShowTitle : 2,
  maxTokensPlay : 0,
  pointsPerSuccess : 5,
  numInitialLives : 5,
  defaultNumQuestions : 15,

  defaultLocale : 'ca',

  colRegular : 'info',
  colFail : 'danger',

  countries : [
    {id: '0', flag: '🇦🇨', name: 'Ascension Island'},
    {id: '1', flag: '🇦🇩', name: 'Andorra'},
    {id: '2', flag: '🇦🇪', name: 'United Arab Emirates'},
    {id: '3', flag: '🇦🇫', name: 'Afghanistan'},
    {id: '4', flag: '🇦🇬', name: 'Antigua & Barbuda'},
    {id: '5', flag: '🇦🇮', name: 'Anguilla'},
    {id: '6', flag: '🇦🇱', name: 'Albania'},
    {id: '7', flag: '🇦🇲', name: 'Armenia'},
    {id: '8', flag: '🇦🇴', name: 'Angola'},
    {id: '9', flag: '🇦🇶', name: 'Antarctica'},
    {id: '10', flag: '🇦🇷', name: 'Argentina'},
    {id: '11', flag: '🇦🇸', name: 'American Samoa'},
    {id: '12', flag: '🇦🇹', name: 'Austria'},
    {id: '13', flag: '🇦🇺', name: 'Australia'},
    {id: '14', flag: '🇦🇼', name: 'Aruba'},
    {id: '15', flag: '🇦🇽', name: 'Åland Islands'},
    {id: '16', flag: '🇦🇿', name: 'Azerbaijan'},
    {id: '17', flag: '🇧🇦', name: 'Bosnia & Herzegovina'},
    {id: '18', flag: '🇧🇧', name: 'Barbados'},
    {id: '19', flag: '🇧🇩', name: 'Bangladesh'},
    {id: '20', flag: '🇧🇪', name: 'Belgium'},
    {id: '21', flag: '🇧🇫', name: 'Burkina Faso'},
    {id: '22', flag: '🇧🇬', name: 'Bulgaria'},
    {id: '23', flag: '🇧🇭', name: 'Bahrain'},
    {id: '24', flag: '🇧🇮', name: 'Burundi'},
    {id: '25', flag: '🇧🇯', name: 'Benin'},
    {id: '26', flag: '🇧🇱', name: 'St. Barthélemy'},
    {id: '27', flag: '🇧🇲', name: 'Bermuda'},
    {id: '28', flag: '🇧🇳', name: 'Brunei'},
    {id: '29', flag: '🇧🇴', name: 'Bolivia'},
    {id: '30', flag: '🇧🇶', name: 'Caribbean Netherlands'},
    {id: '31', flag: '🇧🇷', name: 'Brazil'},
    {id: '32', flag: '🇧🇸', name: 'Bahamas'},
    {id: '33', flag: '🇧🇹', name: 'Bhutan'},
    {id: '34', flag: '🇧🇻', name: 'Bouvet Island'},
    {id: '35', flag: '🇧🇼', name: 'Botswana'},
    {id: '36', flag: '🇧🇾', name: 'Belarus'},
    {id: '37', flag: '🇧🇿', name: 'Belize'},
    {id: '38', flag: '🇨🇦', name: 'Canada'},
    {id: '39', flag: '🇨🇨', name: 'Cocos (Keeling) Islands'},
    {id: '40', flag: '🇨🇩', name: 'Congo - Kinshasa'},
    {id: '41', flag: '🇨🇫', name: 'Central African Republic'},
    {id: '42', flag: '🇨🇬', name: 'Congo - Brazzaville'},
    {id: '43', flag: '🇨🇭', name: 'Switzerland'},
    {id: '44', flag: '🇨🇮', name: 'Côte D’Ivoire'},
    {id: '45', flag: '🇨🇰', name: 'Cook Islands'},
    {id: '46', flag: '🇨🇱', name: 'Chile'},
    {id: '47', flag: '🇨🇲', name: 'Cameroon'},
    {id: '48', flag: '🇨🇳', name: 'China'},
    {id: '49', flag: '🇨🇴', name: 'Colombia'},
    {id: '50', flag: '🇨🇵', name: 'Clipperton Island'},
    {id: '51', flag: '🇨🇷', name: 'Costa Rica'},
    {id: '52', flag: '🇨🇺', name: 'Cuba'},
    {id: '53', flag: '🇨🇻', name: 'Cape Verde'},
    {id: '54', flag: '🇨🇼', name: 'Curaçao'},
    {id: '55', flag: '🇨🇽', name: 'Christmas Island'},
    {id: '56', flag: '🇨🇾', name: 'Cyprus'},
    {id: '57', flag: '🇨🇿', name: 'Czechia'},
    {id: '58', flag: '🇩🇪', name: 'Germany'},
    {id: '59', flag: '🇩🇬', name: 'Diego Garcia'},
    {id: '60', flag: '🇩🇯', name: 'Djibouti'},
    {id: '61', flag: '🇩🇰', name: 'Denmark'},
    {id: '62', flag: '🇩🇲', name: 'Dominica'},
    {id: '63', flag: '🇩🇴', name: 'Dominican Republic'},
    {id: '64', flag: '🇩🇿', name: 'Algeria'},
    {id: '65', flag: '🇪🇦', name: 'Ceuta & Melilla'},
    {id: '66', flag: '🇪🇨', name: 'Ecuador'},
    {id: '67', flag: '🇪🇪', name: 'Estonia'},
    {id: '68', flag: '🇪🇬', name: 'Egypt'},
    {id: '69', flag: '🇪🇭', name: 'Western Sahara'},
    {id: '70', flag: '🇪🇷', name: 'Eritrea'},
    {id: '71', flag: '🇪🇸', name: 'Spain'},
    {id: '72', flag: '🇪🇹', name: 'Ethiopia'},
    {id: '73', flag: '🇪🇺', name: 'European Union'},
    {id: '74', flag: '🇫🇮', name: 'Finland'},
    {id: '75', flag: '🇫🇯', name: 'Fiji'},
    {id: '76', flag: '🇫🇰', name: 'Falkland Islands'},
    {id: '77', flag: '🇫🇲', name: 'Micronesia'},
    {id: '78', flag: '🇫🇴', name: 'Faroe Islands'},
    {id: '79', flag: '🇫🇷', name: 'France'},
    {id: '80', flag: '🇬🇦', name: 'Gabon'},
    {id: '81', flag: '🇬🇧', name: 'United Kingdom'},
    {id: '82', flag: '🇬🇩', name: 'Grenada'},
    {id: '83', flag: '🇬🇪', name: 'Georgia'},
    {id: '84', flag: '🇬🇫', name: 'French Guiana'},
    {id: '85', flag: '🇬🇬', name: 'Guernsey'},
    {id: '86', flag: '🇬🇭', name: 'Ghana'},
    {id: '87', flag: '🇬🇮', name: 'Gibraltar'},
    {id: '88', flag: '🇬🇱', name: 'Greenland'},
    {id: '89', flag: '🇬🇲', name: 'Gambia'},
    {id: '90', flag: '🇬🇳', name: 'Guinea'},
    {id: '91', flag: '🇬🇵', name: 'Guadeloupe'},
    {id: '92', flag: '🇬🇶', name: 'Equatorial Guinea'},
    {id: '93', flag: '🇬🇷', name: 'Greece'},
    {id: '95', flag: '🇬🇹', name: 'Guatemala'},
    {id: '96', flag: '🇬🇺', name: 'Guam'},
    {id: '97', flag: '🇬🇼', name: 'Guinea-Bissau'},
    {id: '98', flag: '🇬🇾', name: 'Guyana'},
    {id: '99', flag: '🇭🇰', name: 'Hong Kong Sar China'},
    {id: '101', flag: '🇭🇳', name: 'Honduras'},
    {id: '102', flag: '🇭🇷', name: 'Croatia'},
    {id: '103', flag: '🇭🇹', name: 'Haiti'},
    {id: '104', flag: '🇭🇺', name: 'Hungary'},
    {id: '105', flag: '🇮🇨', name: 'Canary Islands'},
    {id: '106', flag: '🇮🇩', name: 'Indonesia'},
    {id: '107', flag: '🇮🇪', name: 'Ireland'},
    {id: '108', flag: '🇮🇱', name: 'Israel'},
    {id: '109', flag: '🇮🇲', name: 'Isle of Man'},
    {id: '110', flag: '🇮🇳', name: 'India'},
    {id: '112', flag: '🇮🇶', name: 'Iraq'},
    {id: '113', flag: '🇮🇷', name: 'Iran'},
    {id: '114', flag: '🇮🇸', name: 'Iceland'},
    {id: '115', flag: '🇮🇹', name: 'Italy'},
    {id: '116', flag: '🇯🇪', name: 'Jersey'},
    {id: '117', flag: '🇯🇲', name: 'Jamaica'},
    {id: '118', flag: '🇯🇴', name: 'Jordan'},
    {id: '119', flag: '🇯🇵', name: 'Japan'},
    {id: '120', flag: '🇰🇪', name: 'Kenya'},
    {id: '121', flag: '🇰🇬', name: 'Kyrgyzstan'},
    {id: '122', flag: '🇰🇭', name: 'Cambodia'},
    {id: '123', flag: '🇰🇮', name: 'Kiribati'},
    {id: '124', flag: '🇰🇲', name: 'Comoros'},
    {id: '125', flag: '🇰🇳', name: 'St. Kitts & Nevis'},
    {id: '126', flag: '🇰🇵', name: 'North Korea'},
    {id: '127', flag: '🇰🇷', name: 'South Korea'},
    {id: '128', flag: '🇰🇼', name: 'Kuwait'},
    {id: '129', flag: '🇰🇾', name: 'Cayman Islands'},
    {id: '130', flag: '🇰🇿', name: 'Kazakhstan'},
    {id: '131', flag: '🇱🇦', name: 'Laos'},
    {id: '132', flag: '🇱🇧', name: 'Lebanon'},
    {id: '133', flag: '🇱🇨', name: 'St. Lucia'},
    {id: '134', flag: '🇱🇮', name: 'Liechtenstein'},
    {id: '135', flag: '🇱🇰', name: 'Sri Lanka'},
    {id: '136', flag: '🇱🇷', name: 'Liberia'},
    {id: '137', flag: '🇱🇸', name: 'Lesotho'},
    {id: '138', flag: '🇱🇹', name: 'Lithuania'},
    {id: '139', flag: '🇱🇺', name: 'Luxembourg'},
    {id: '140', flag: '🇱🇻', name: 'Latvia'},
    {id: '141', flag: '🇱🇾', name: 'Libya'},
    {id: '142', flag: '🇲🇦', name: 'Morocco'},
    {id: '143', flag: '🇲🇨', name: 'Monaco'},
    {id: '144', flag: '🇲🇩', name: 'Moldova'},
    {id: '145', flag: '🇲🇪', name: 'Montenegro'},
    {id: '146', flag: '🇲🇫', name: 'St. Martin'},
    {id: '147', flag: '🇲🇬', name: 'Madagascar'},
    {id: '148', flag: '🇲🇭', name: 'Marshall Islands'},
    {id: '149', flag: '🇲🇰', name: 'Macedonia'},
    {id: '150', flag: '🇲🇱', name: 'Mali'},
    {id: '151', flag: '🇲🇲', name: 'Myanmar (Burma)'},
    {id: '152', flag: '🇲🇳', name: 'Mongolia'},
    {id: '153', flag: '🇲🇴', name: 'Macau Sar China'},
    {id: '154', flag: '🇲🇵', name: 'Northern Mariana Islands'},
    {id: '155', flag: '🇲🇶', name: 'Martinique'},
    {id: '156', flag: '🇲🇷', name: 'Mauritania'},
    {id: '157', flag: '🇲🇸', name: 'Montserrat'},
    {id: '158', flag: '🇲🇹', name: 'Malta'},
    {id: '159', flag: '🇲🇺', name: 'Mauritius'},
    {id: '160', flag: '🇲🇻', name: 'Maldives'},
    {id: '161', flag: '🇲🇼', name: 'Malawi'},
    {id: '162', flag: '🇲🇽', name: 'Mexico'},
    {id: '163', flag: '🇲🇾', name: 'Malaysia'},
    {id: '164', flag: '🇲🇿', name: 'Mozambique'},
    {id: '165', flag: '🇳🇦', name: 'Namibia'},
    {id: '166', flag: '🇳🇨', name: 'New Caledonia'},
    {id: '167', flag: '🇳🇪', name: 'Niger'},
    {id: '168', flag: '🇳🇫', name: 'Norfolk Island'},
    {id: '169', flag: '🇳🇬', name: 'Nigeria'},
    {id: '170', flag: '🇳🇮', name: 'Nicaragua'},
    {id: '171', flag: '🇳🇱', name: 'Netherlands'},
    {id: '172', flag: '🇳🇴', name: 'Norway'},
    {id: '173', flag: '🇳🇵', name: 'Nepal'},
    {id: '174', flag: '🇳🇷', name: 'Nauru'},
    {id: '175', flag: '🇳🇺', name: 'Niue'},
    {id: '176', flag: '🇳🇿', name: 'New Zealand'},
    {id: '177', flag: '🇴🇲', name: 'Oman'},
    {id: '178', flag: '🇵🇦', name: 'Panama'},
    {id: '179', flag: '🇵🇪', name: 'Peru'},
    {id: '180', flag: '🇵🇫', name: 'French Polynesia'},
    {id: '181', flag: '🇵🇬', name: 'Papua New Guinea'},
    {id: '182', flag: '🇵🇭', name: 'Philippines'},
    {id: '183', flag: '🇵🇰', name: 'Pakistan'},
    {id: '184', flag: '🇵🇱', name: 'Poland'},
    {id: '185', flag: '🇵🇲', name: 'St. Pierre & Miquelon'},
    {id: '186', flag: '🇵🇳', name: 'Pitcairn Islands'},
    {id: '187', flag: '🇵🇷', name: 'Puerto Rico'},
    {id: '188', flag: '🇵🇸', name: 'Palestinian Territories'},
    {id: '189', flag: '🇵🇹', name: 'Portugal'},
    {id: '190', flag: '🇵🇼', name: 'Palau'},
    {id: '191', flag: '🇵🇾', name: 'Paraguay'},
    {id: '192', flag: '🇶🇦', name: 'Qatar'},
    {id: '193', flag: '🇷🇪', name: 'Réunion'},
    {id: '194', flag: '🇷🇴', name: 'Romania'},
    {id: '195', flag: '🇷🇸', name: 'Serbia'},
    {id: '196', flag: '🇷🇺', name: 'Russia'},
    {id: '197', flag: '🇷🇼', name: 'Rwanda'},
    {id: '198', flag: '🇸🇦', name: 'Saudi Arabia'},
    {id: '199', flag: '🇸🇧', name: 'Solomon Islands'},
    {id: '200', flag: '🇸🇨', name: 'Seychelles'},
    {id: '201', flag: '🇸🇩', name: 'Sudan'},
    {id: '202', flag: '🇸🇪', name: 'Sweden'},
    {id: '203', flag: '🇸🇬', name: 'Singapore'},
    {id: '204', flag: '🇸🇭', name: 'St. Helena'},
    {id: '205', flag: '🇸🇮', name: 'Slovenia'},
    {id: '206', flag: '🇸🇯', name: 'Svalbard & Jan Mayen'},
    {id: '207', flag: '🇸🇰', name: 'Slovakia'},
    {id: '208', flag: '🇸🇱', name: 'Sierra Leone'},
    {id: '209', flag: '🇸🇲', name: 'San Marino'},
    {id: '210', flag: '🇸🇳', name: 'Senegal'},
    {id: '211', flag: '🇸🇴', name: 'Somalia'},
    {id: '212', flag: '🇸🇷', name: 'Suriname'},
    {id: '213', flag: '🇸🇸', name: 'South Sudan'},
    {id: '214', flag: '🇸🇹', name: 'São Tomé & Príncipe'},
    {id: '215', flag: '🇸🇻', name: 'El Salvador'},
    {id: '216', flag: '🇸🇽', name: 'Sint Maarten'},
    {id: '217', flag: '🇸🇾', name: 'Syria'},
    {id: '218', flag: '🇸🇿', name: 'Swaziland'},
    {id: '219', flag: '🇹🇦', name: 'Tristan Da Cunha'},
    {id: '220', flag: '🇹🇨', name: 'Turks & Caicos Islands'},
    {id: '221', flag: '🇹🇩', name: 'Chad'},
    {id: '222', flag: '🇹🇫', name: 'French Southern Territories'},
    {id: '223', flag: '🇹🇬', name: 'Togo'},
    {id: '224', flag: '🇹🇭', name: 'Thailand'},
    {id: '225', flag: '🇹🇯', name: 'Tajikistan'},
    {id: '226', flag: '🇹🇰', name: 'Tokelau'},
    {id: '227', flag: '🇹🇱', name: 'Timor-Leste'},
    {id: '228', flag: '🇹🇲', name: 'Turkmenistan'},
    {id: '229', flag: '🇹🇳', name: 'Tunisia'},
    {id: '230', flag: '🇹🇴', name: 'Tonga'},
    {id: '231', flag: '🇹🇷', name: 'Turkey'},
    {id: '232', flag: '🇹🇹', name: 'Trinidad & Tobago'},
    {id: '233', flag: '🇹🇻', name: 'Tuvalu'},
    {id: '234', flag: '🇹🇼', name: 'Taiwan'},
    {id: '235', flag: '🇹🇿', name: 'Tanzania'},
    {id: '236', flag: '🇺🇦', name: 'Ukraine'},
    {id: '237', flag: '🇺🇬', name: 'Uganda'},
    {id: '238', flag: '🇺🇸', name: 'United States'},
    {id: '239', flag: '🇺🇾', name: 'Uruguay'},
    {id: '240', flag: '🇺🇿', name: 'Uzbekistan'},
    {id: '241', flag: '🇻🇦', name: 'Vatican City'},
    {id: '242', flag: '🇻🇨', name: 'St. Vincent & Grenadines'},
    {id: '243', flag: '🇻🇪', name: 'Venezuela'},
    {id: '244', flag: '🇻🇬', name: 'British Virgin Islands'},
    {id: '245', flag: '🇻🇮', name: 'U.S. Virgin Islands'},
    {id: '246', flag: '🇻🇳', name: 'Vietnam'},
    {id: '247', flag: '🇻🇺', name: 'Vanuatu'},
    {id: '248', flag: '🇼🇫', name: 'Wallis & Futuna'},
    {id: '249', flag: '🇼🇸', name: 'Samoa'},
    {id: '250', flag: '🇽🇰', name: 'Kosovo'},
    {id: '251', flag: '🇾🇪', name: 'Yemen'},
    {id: '252', flag: '🇾🇹', name: 'Mayotte'},
    {id: '253', flag: '🇿🇦', name: 'South Africa'},
    {id: '254', flag: '🇿🇲', name: 'Zambia'},
    {id: '255', flag: '🇿🇼', name: 'Zimbabwe'}
  ]
};
